version: "3.7"

services:
<<<<<<< HEAD
  web:
    build: ./shap-django
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn --bind 0.0.0.0:8000 shap_django.wsgi:application # new
    volumes:
      - .:/code
=======
  backend:
    build:
      context: ./shap-django
    command: gunicorn shap_django.wsgi:application --bind 0.0.0.0:8000 # new
    volumes:
      - ./shap-django:/code
    env_file:
      - ./.env
>>>>>>> 1934c9e76d248d5b2105ca91a2705511911122d1
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=${SECRET_KEY} # here it is
      - DEBUG=${DEBUG}
      - ENVIRONMENT=${ENVIRONMENT_DEV}
      - REDIS_URL=${REDIS_URL}
  #   links:
  #     - redis
  #   depends_on:
  #     - redis

<<<<<<< HEAD
  # redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
=======
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  celery:
    build: ./shap-django
    volumes:
      - .:/src
    command: celery -A shap_django worker #-l info
    links:
      - redis

  frontend:
    build:
      context: ./shap-react
      dockerfile: Dockerfile.prod
    volumes:
      - ./shap-react/build:/src

  nginx:
    image: nginx:latest
    ports:
      - 80:8080 #request enters at port 80 and are processed by ngnix at port 8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./shap-react/build:/var/www/react

    depends_on:
      - backend
      - frontend
>>>>>>> 1934c9e76d248d5b2105ca91a2705511911122d1

  # celery:
  #   build: ./shap-django
  #   volumes:
  #     - .:/src
  #   # container_name: cl01
  #   command: celery -A shap_django worker #-l info
  #   links:
  #     - redis
