version: "3.8"

services:
  backend:
    build:
      context: ./shap-django
    command: gunicorn shap_django.wsgi:application --bind 0.0.0.0:8000 # new
    volumes:
      - ./shap-django:/code
    env_file:
      - ./.env
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=${SECRET_KEY} # here it is
      - DEBUG=${DEBUG}
      - ENVIRONMENT=${ENVIRONMENT_DEV}
      - REDIS_URL=${REDIS_URL}
    links:
      - redis
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  celery:
    build: ./shap-django
    volumes:
      - .:/src
    command: celery -A shap_django worker #-l info
    links:
      - redis

  frontend:
    build: ./shap-react
    volumes:
      - ./shap-react/build:/src

  nginx:
    image: nginx:latest
    ports:
      - 80:8080 #request enters at port 80 and are processed by ngnix at port 8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./shap-react/build:/var/www/react

    depends_on:
      - backend
      - frontend

volumes:
  build:
